name: ci
env:
  go_version: '1.22.x'
  go_versions: '["1.20.x","1.21.x","1.22.x"]'
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ${{ fromJSON(vars.GO_VERSIONS) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Unit Test
        run: make shorttest
      - name: Lint
        # Often, lint & gofmt guidelines depend on the Go version. To prevent
        # conflicting guidance, run only on the most recent supported version.
        # For the same reason, only check generated code on the most recent
        # supported version.
        if: matrix.go-version == ${{ vars.GO-VERSION }}
        run: make checkgenerate && make lint
  conformance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ${{ fromJSON(vars.GO_VERSIONS) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run Conformance Tests
        run: make runconformance
  slowtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          # only the latest
          go-version: ${{ vars.GO_VERSION }}
      - name: Run Slow Tests
        run: make slowtest
